class RemoteConnection:
    host: str
    port: int

    def __init__(self, host: str, port: int, *args, **kwargs) -> None: ...
    def close(self) -> None: ...
    def send(self, data) -> int: ...
    def sendline(self, data=...) -> int: ...
    def recv(self, numb: int = ..., timeout=...) -> bytes: ...
    def recvn(self, numb: int, timeout=...) -> bytes: ...
    def recvuntil(self, delim, drop: bool = ..., timeout=...) -> bytes: ...
    def recvline(self, keepends: bool = ..., drop=..., timeout=...) -> bytes: ...
    def sendafter(self, delim, data) -> int: ...
    def sendlineafter(self, delim, data) -> int: ...
    def interactive(self) -> None: ...


def remote(host: str, port: int, *args, **kwargs) -> RemoteConnection: ...
